version: "3"
services:
  peer1:
    image: zhangzexu/bolg-registry-center:1.0.3
    restart: on-failure
    ports:
      - 8761:8761
    environment:
      - spring.profiles.active=peer1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  peer2:
    image: zhangzexu/bolg-registry-center:1.0.3
    restart: on-failure
    ports:
      - 8762:8762
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - spring.profiles.active=peer2
  bolg-web-ui:
    image: zhangzexu/bolg-web-ui:1.0-SNAPSHOT
    restart: on-failure
    ports:
      - 8081:8081
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  bolg-web-admin:
    image: zhangzexu/bolg-web-admin:1.0-SNAPSHOT
    restart: on-failure
    ports:
      - 9000:9000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
networks:
  default:
    external:
      name: my_net

