spring:
  application:
    name: bolg-registry-center
  cloud:
    inetutils:
      preferred-networks:
        - 10.0
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
